In [2]:
import pandas as pd

In [3]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [16]:
df = pd.read_csv('./Session 8.csv')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

Single column = series;
multiple rows and column = data frame

In [18]:
df['Ship Mode']

0         Second Class
1         Second Class
2         Second Class
3       Standard Class
4       Standard Class
             ...
9989      Second Class
9990    Standard Class
9991    Standard Class
9992    Standard Class
9993      Second Class
Name: Ship Mode, Length: 9994, dtype: object

In [19]:
df['Ship Mode'].astype('string')

0         Second Class
1         Second Class
2         Second Class
3       Standard Class
4       Standard Class
             ...
9989      Second Class
9990    Standard Class
9991    Standard Class
9992    Standard Class
9993      Second Class
Name: Ship Mode, Length: 9994, dtype: string

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [21]:
df['Ship Mode'] = df['Ship Mode'].astype('string')

In [23]:
df['Segment'] = df['Segment'].astype('string')

In [24]:
df['Country'] = df['Country'].astype('string')

In [25]:
df['City'] = df['City'].astype('string')

In [26]:
df['State'] = df['State'].astype('string')

In [27]:
df['Postal Code'] = df['Postal Code'].astype('string')

In [28]:
df['Region'] = df['Region'].astype('string')

In [29]:
df['Category'] = df['Category'].astype('string')

In [30]:
df['Sub-Category'] = df['Sub-Category'].astype('string')

In [43]:
df['Sales'] = df['Sales'].astype('string')

In [44]:
df['Quantity'] = df['Quantity'].astype('string')

In [45]:
df['Discount'] = df['Discount'].astype('string')

In [46]:
df['Profit'] = df['Profit'].astype('string')

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   string
 1   Segment       9994 non-null   string
 2   Country       9994 non-null   string
 3   City          9994 non-null   string
 4   State         9994 non-null   string
 5   Postal Code   9994 non-null   string
 6   Region        9994 non-null   string
 7   Category      9994 non-null   string
 8   Sub-Category  9994 non-null   string
 9   Sales         9994 non-null   string
 10  Quantity      9994 non-null   string
 11  Discount      9994 non-null   string
 12  Profit        9994 non-null   string
dtypes: string(13)
memory usage: 1015.1 KB

In [48]:
df.dtypes

Ship Mode       string[python]
Segment         string[python]
Country         string[python]
City            string[python]
State           string[python]
Postal Code     string[python]
Region          string[python]
Category        string[python]
Sub-Category    string[python]
Sales           string[python]
Quantity        string[python]
Discount        string[python]
Profit          string[python]
dtype: object

In [49]:
df['Sales'] = df['Sales'].astype('float64')

In [50]:
df['Profit'] = df['Profit'].astype('float64')

In [51]:
df['Discount'] = df['Discount'].astype('float64')

In [52]:
df['Quantity'] = df['Quantity'].astype('int64')

In [53]:
df.dtypes

Ship Mode       string[python]
Segment         string[python]
Country         string[python]
City            string[python]
State           string[python]
Postal Code     string[python]
Region          string[python]
Category        string[python]
Sub-Category    string[python]
Sales                  float64
Quantity                 int64
Discount               float64
Profit                 float64
dtype: object

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   string
 1   Segment       9994 non-null   string
 2   Country       9994 non-null   string
 3   City          9994 non-null   string
 4   State         9994 non-null   string
 5   Postal Code   9994 non-null   string
 6   Region        9994 non-null   string
 7   Category      9994 non-null   string
 8   Sub-Category  9994 non-null   string
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(1), string(9)
memory usage: 1015.1 KB

In [55]:
df.shape

(9994, 13)

In [56]:
df.loc[3]

Ship Mode        Standard Class
Segment                Consumer
Country           United States
City            Fort Lauderdale
State                   Florida
Postal Code               33311
Region                    South
Category              Furniture
Sub-Category             Tables
Sales                  957.5775
Quantity                      5
Discount                   0.45
Profit                 -383.031
Name: 3, dtype: object

In [59]:
df.loc[3]['Segment']

'Consumer'

In [60]:
df.loc[3, 'Segment']

'Consumer'

In [57]:
df.iloc[3]

Ship Mode        Standard Class
Segment                Consumer
Country           United States
City            Fort Lauderdale
State                   Florida
Postal Code               33311
Region                    South
Category              Furniture
Sub-Category             Tables
Sales                  957.5775
Quantity                      5
Discount                   0.45
Profit                 -383.031
Name: 3, dtype: object

In [61]:
df.iloc[3, 1]

'Consumer'

In [62]:
df.iloc[3][1]

C:\Users\Zubair Naseer\AppData\Local\Temp\ipykernel_21328\3292216812.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[3][1]

'Consumer'

In [63]:
df.loc[2:10]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092

In [64]:
df.iloc[2:10]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
5,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [66]:
df.iloc[2:10, 1:-3]

,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales
2,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200
3,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775
4,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680
5,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600
6,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800
7,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520
8,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040
9,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000

In [67]:
df.iloc[2:10, 1:10]

,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales
2,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200
3,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775
4,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680
5,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600
6,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800
7,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520
8,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040
9,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000

In [68]:
df.loc[2:9, 'Segment':'Sales']

,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales
2,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200
3,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775
4,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680
5,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600
6,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800
7,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520
8,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040
9,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000

In df.loc[] both indexes are included
In df.iloc[] last index is excluded

In [74]:
# state, sales, quantity
df.loc[2:9, ['State', 'Sales', 'Quantity']]

        State     Sales  Quantity
2  California   14.6200         2
3     Florida  957.5775         5
4     Florida   22.3680         2
5  California   48.8600         7
6  California    7.2800         4
7  California  907.1520         6
8  California   18.5040         3
9  California  114.9000         5

In [76]:
df.iloc[2:10, [4, 9, 10]]

        State     Sales  Quantity
2  California   14.6200         2
3     Florida  957.5775         5
4     Florida   22.3680         2
5  California   48.8600         7
6  California    7.2800         4
7  California  907.1520         6
8  California   18.5040         3
9  California  114.9000         5

### not ---> ~
### or ---> |
### and ---> &

# simd = single instruction for multiple data

In [77]:
df['Region'].unique()

<StringArray>
['South', 'West', 'Central', 'East']
Length: 4, dtype: string

In [78]:
df['Region'] == 'South'

0        True
1        True
2       False
3        True
4        True
        ...
9989     True
9990    False
9991    False
9992    False
9993    False
Name: Region, Length: 9994, dtype: boolean

In [79]:
df[df['Region'] == 'South']

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
12,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,15.5520,3,0.20,5.4432
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9971,Standard Class,Home Office,United States,Smyrna,Georgia,30080,South,Office Supplies,Art,140.7500,5,0.00,42.2250
9980,Second Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Tables,85.9800,1,0.00,22.3548
9987,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Accessories,79.9900,1,0.00,28.7964
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.1000,5,0.00,55.6470
9989,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028

In [82]:
df[df['Sales'] > 200]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,249.5840,2,0.20,31.1980
9979,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,437.4720,14,0.20,153.1152
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.1000,5,0.00,55.6470
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [84]:
(df['Sales'] > 200) & (df['Region'] == 'South')

0        True
1        True
2       False
3        True
4       False
        ...
9989    False
9990    False
9991    False
9992    False
9993    False
Length: 9994, dtype: boolean

In [85]:
df[(df['Sales'] > 200) & (df['Region'] == 'South')]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
72,Standard Class,Consumer,United States,Memphis,Tennessee,38109,South,Furniture,Chairs,831.9360,8,0.20,-114.3912
79,First Class,Corporate,United States,Decatur,Alabama,35601,South,Office Supplies,Appliances,208.1600,1,0.00,56.2032
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9769,Standard Class,Home Office,United States,Hialeah,Florida,33012,South,Furniture,Bookcases,339.9200,5,0.20,8.4980
9816,Standard Class,Corporate,United States,Saint Petersburg,Florida,33710,South,Office Supplies,Storage,516.9600,4,0.20,-6.4620
9829,Standard Class,Consumer,United States,Charlotte,North Carolina,28205,South,Furniture,Chairs,242.3520,3,0.20,15.1470
9882,First Class,Consumer,United States,Woodstock,Georgia,30188,South,Technology,Accessories,272.6100,13,0.00,98.1396
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.1000,5,0.00,55.6470

In [92]:
pd.options.display.max_rows = None # = 100 means 100 rows

In [93]:
df[(df['Sales'] > 200) & (df['Region'] == 'South')]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
72,Standard Class,Consumer,United States,Memphis,Tennessee,38109,South,Furniture,Chairs,831.9360,8,0.20,-114.3912
79,First Class,Corporate,United States,Decatur,Alabama,35601,South,Office Supplies,Appliances,208.1600,1,0.00,56.2032
83,Standard Class,Corporate,United States,Durham,North Carolina,27707,South,Office Supplies,Envelopes,200.9840,7,0.20,62.8075
85,Second Class,Consumer,United States,Columbia,South Carolina,29203,South,Furniture,Chairs,301.9600,2,0.00,33.2156
182,Second Class,Home Office,United States,Monroe,Louisiana,71203,South,Technology,Phones,503.9600,4,0.00,131.0296
229,Standard Class,Consumer,United States,Columbia,Tennessee,38401,South,Furniture,Chairs,389.6960,8,0.20,43.8408
231,Standard Class,Home Office,United States,Tampa,Florida,33614,South,Furniture,Tables,233.8600,2,0.45,-102.0480
232,Standard Class,Home Office,United States,Tampa,Florida,33614,South,Furniture,Tables,620.6145,3,0.45,-248.2458
234,Standard Class,Home Office,United States,Tampa,Florida,33614,South,Furniture,Furnishings,258.0720,3,0.20,0.0000
235,Standard Class,Home Office,United States,Tampa,Florida,33614,South,Technology,Accessories,617.9760,3,0.20,-7.7247
286,Second Class,Corporate,United States,Tamarac,Florida,33319,South,Office Supplies,Binders,254.0580,7,0.70,-169.3720
288,Second Class,Corporate,United States,Tamarac,Florida,33319,South,Office Supplies,Supplies,961.4800,5,0.20,-204.3145
359,First Class,Corporate,United States,Columbus,Georgia,31907,South,Office Supplies,Appliances,647.8400,8,0.00,168.4384
384,Standard Class,Consumer,United States,Pembroke Pines,Florida,33024,South,Furniture,Tables,375.4575,3,0.45,-157.0095
424,Second Class,Consumer,United States,Jackson,Mississippi,39212,South,Furniture,Chairs,866.4000,4,0.00,225.2640
430,Standard Class,Home Office,United States,Gastonia,North Carolina,28052,South,Technology,Accessories,408.7440,7,0.20,76.6395
431,Standard Class,Home Office,United States,Gastonia,North Carolina,28052,South,Technology,Accessories,291.9600,5,0.20,54.7425
435,Standard Class,Consumer,United States,Jacksonville,Florida,32216,South,Technology,Accessories,247.8000,5,0.20,-18.5850
509,Standard Class,Consumer,United States,Atlanta,Georgia,30318,South,Office Supplies,Binders,6354.9500,5,0.00,3177.4750
526,Standard Class,Home Office,United States,Lakeland,Florida,33801,South,Furniture,Chairs,683.9520,3,0.20,42.7470
533,Second Class,Consumer,United States,Montgomery,Alabama,36116,South,Technology,Phones,979.9500,5,0.00,274.3860
539,Standard Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,283.9200,4,0.00,70.9800
587,Standard Class,Consumer,United States,Richmond,Kentucky,40475,South,Office Supplies,Labels,294.9300,3,0.00,144.5157
634,Second Class,Consumer,United States,Miami,Florida,33180,South,Office Supplies,Labels,235.9440,3,0.20,85.5297
635,Second Class,Corporate,United States,Warner Robins,Georgia,31088,South,Furniture,Chairs,392.9400,3,0.00,43.2234
683,Same Day,Corporate,United States,Burlington,North Carolina,27217,South,Technology,Machines,7999.9800,4,0.50,-3839.9904
685,First Class,Consumer,United States,Jackson,Mississippi,39212,South,Technology,Accessories,479.9700,3,0.00,163.1898
690,Second Class,Consumer,United States,Waynesboro,Virginia,22980,South,Technology,Phones,284.8200,1,0.00,74.0532
755,Standard Class,Corporate,United States,Jacksonville,Florida,32216,South,Furniture,Tables,383.4380,4,0.45,-167.3184
765,Second Class,Corporate,United States,Bossier City,Louisiana,71111,South,Technology,Accessories,646.7400,6,0.00,258.6960
767,Second Class,Corporate,United States,Bossier City,Louisiana,71111,South,Office Supplies,Storage,572.5800,6,0.00,34.3548
768,Standard Class,Corporate,United States,Saint Petersburg,Florida,33710,South,Furniture,Furnishings,310.8800,2,0.20,23.3160
769,Standard Class,Consumer,United States,Arlington,Virginia,22204,South,Furniture,Chairs,641.9600,2,0.00,179.7488
791,Standard Class,Consumer,United States,Richmond,Virginia,23223,South,Furniture,Chairs,332.9400,3,0.00,79.9056
792,Same Day,Consumer,United States,Asheville,North Carolina,28806,South,Technology,Phones,1363.9600,5,0.20,85.2475
829,Second Class,Consumer,United States,Florence,Kentucky,41042,South,Furniture,Chairs,301.9600,2,0.00,90.5880
835,Standard Class,Corporate,United States,Tampa,Florida,33614,South,Technology,Machines,265.4750,1,0.50,-111.4995
847,Standard Class,Consumer,United States,Louisville,Kentucky,40214,South,Furniture,Chairs,287.9400,3,0.00,77.7438
990,Second Class,Home Office,United States,Jacksonville,Florida,32216,South,Furniture,Chairs,1166.9200,5,0.20,131.2785
994,Standard Class,Corporate,United States,Virginia Beach,Virginia,23464,South,Office Supplies,Binders,2715.9300,7,0.00,1276.4871
995,Standard Class,Corporate,United States,Virginia Beach,Virginia,23464,South,Technology,Phones,617.9700,3,0.00,173.0316
1046,Standard Class,Consumer,United States,Miami,Florida,33142,South,Technology,Phones,1363.9600,5,0.20,85.2475
1095,Standard Class,Home Office,United States,Charlotte,North Carolina,28205,South,Office Supplies,Storage,348.2080,7,0.20,30.4682
1117,Standard Class,Consumer,United States,Roswell,Georgia,30076,South,Office Supplies,Paper,279.9000,5,0.00,137.1510
1118,Standard Class,Consumer,United States,Roswell,Georgia,30076,South,Technology,Accessories,619.9500,5,0.00,111.5910
1121,Standard Class,Consumer,United States,Jonesboro,Arkansas,72401,South,Technology,Phones,699.9300,7,0.00,181.9818
1126,Standard Class,Consumer,United States,Jonesboro,Arkansas,72401,South,Furniture,Chairs,1067.9400,3,0.00,224.2674
1129,Standard Class,Consumer,United States,Springfield,Virginia,22153,South,Furniture,Tables,343.9200,4,0.00,75.6624
1155,First Class,Home Office,United States,Harrisonburg,Virginia,22801,South,Furniture,Tables,2244.4800,7,0.00,493.7856
1157,First Class,Home Office,United States,Harrisonburg,Virginia,22801,South,Furniture,Tables,455.1000,2,0.00,100.1220
1205,First Class,Consumer,United States,Charlotte,North Carolina,28205,South,Technology,Phones,271.9600,5,0.20,16.9975
1258,Second Class,Home Office,United States,Charlotte,North Carolina,28205,South,Office Supplies,Storage,540.0480,3,0.20,-47.2542
1259,Second Class,Home Office,United States,Charlotte,North Carolina,28205,South,Technology,Accessories,255.6800,8,0.20,76.7040
1260,Standard Class,Consumer,United States,Jacksonville,Florida,32216,South,Technology,Phones,863.8800,3,0.20,107.9850
1283,First Class,Consumer,United States,Jacksonville,Florida,32216,South,Office Supplies,Paper,251.6400,3,0.20,88.0740
1300,Second Class,Consumer,United States,Springfield,Virginia,22153,South,Furniture,Furnishings,572.7600,6,0.00,166.1004
1301,Second Class,Consumer,United States,Springfield,Virginia,22153,South,Furniture,Furnishings,286.3800,3,0.00,83.0502
1304,Standard Class,Consumer,United States,Columbus,Georgia,31907,South,Technology,Phones,287.9700,3,0.00,77.7519
1318,Standard Class,Corporate,United States,Deltona,Florida,32725,South,Technology,Phones,575.9200,2,0.20,71.9900
1340,First Class,Corporate,United States,Jacksonville,North Carolina,28540,South,Technology,Machines,695.7000,2,0.50,-27.8280
1383,Same Day,Home Office,United States,Smyrna,Georgia,30080,South,Office Supplies,Paper,348.8400,9,0.00,170.9316
1386,Same Day,Home Office,United States,Smyrna,Georgia,30080,South,Furniture,Bookcases,239.9800,2,0.00,52.7956
1389,Same Day,Home Office,United States,Smyrna,Georgia,30080,South,Technology,Phones,484.8300,3,0.00,126.0558
1392,Same Day,Home Office,United States,Smyrna,Georgia,30080,South,Office Supplies,Paper,342.3700,7,0.00,160.9139
1401,Standard Class,Home Office,United States,Salem,Virginia,24153,South,Office Supplies,Envelopes,251.7900,3,0.00,118.3413
1433,Second Class,Consumer,United States,Florence,Alabama,35630,South,Furniture,Chairs,1819.8600,14,0.00,163.7874
1454,First Class,Corporate,United States,Mobile,Alabama,36608,South,Technology,Machines,3040.0000,8,0.00,1459.2000
1456,Standard Class,Home Office,United States,Columbus,Georgia,31907,South,Furniture,Tables,452.9400,3,0.00,67.9410
1467,Same Day,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Accessories,255.9680,4,0.20,31.9960
1507,Standard Class,Consumer,United States,Columbus,Georgia,31907,South,Technology,Machines,396.0000,4,0.00,190.0800
1564,Same Day,Consumer,United States,Columbia,South Carolina,29203,South,Office Supplies,Storage,354.9000,5,0.00,17.7450
1627,Standard Class,Consumer,United States,Lafayette,Louisiana,70506,South,Furniture,Chairs,517.5000,6,0.00,155.2500
1811,Second Class,Consumer,United States,Harrisonburg,Virginia,22801,South,Furniture,Tables,1441.3000,7,0.00,245.0210
1827,Second Class,Home Office,United States,Raleigh,North Carolina,27604,South,Technology,Phones,1127.9760,3,0.20,126.8973
1832,Standard Class,Corporate,United States,Monroe,North Carolina,28110,South,Furniture,Chairs,207.0000,3,0.20,25.8750
1836,Second Class,Corporate,United States,Roswell,Georgia,30076,South,Office Supplies,Appliances,1245.8600,7,0.00,361.2994
1887,First Class,Home Office,United States,Hialeah,Florida,33012,South,Office Supplies,Binders,398.3520,8,0.70,-331.9600
1898,Second Class,Consumer,United States,Miami,Florida,33178,South,Office Supplies,Binders,505.1760,4,0.70,-336.7840
1975,Second Class,Corporate,United States,Montgomery,Alabama,36116,South,Office Supplies,Storage,275.9700,3,0.00,11.0388
1976,Second Class,Corporate,United States,Montgomery,Alabama,36116,South,Technology,Phones,1394.9500,5,0.00,362.6870
1977,Second Class,Corporate,United States,Montgomery,Alabama,36116,South,Furniture,Chairs,545.8800,6,0.00,70.9644
2003,Second Class,Consumer,United States,Louisville,Kentucky,40214,South,Furniture,Chairs,304.4500,5,0.00,76.1125
2009,Standard Class,Consumer,United States,Johnson City,Tennessee,37604,South,Office Supplies,Appliances,333.0560,2,0.20,29.1424
2013,Standard Class,Consumer,United States,Auburn,Alabama,36830,South,Furniture,Chairs,350.9800,1,0.00,84.2352
2015,Standard Class,Consumer,United States,Auburn,Alabama,36830,South,Office Supplies,Storage,900.0800,4,0.00,117.0104
2095,Standard Class,Home Office,United States,Jackson,Mississippi,39212,South,Office Supplies,Binders,511.8400,8,0.00,240.5648
2201,Standard Class,Consumer,United States,Little Rock,Arkansas,72209,South,Technology,Phones,881.9300,7,0.00,229.3018
2262,First Class,Consumer,United States,Arlington,Virginia,22204,South,Furniture,Bookcases,359.9700,3,0.00,79.1934
2263,Second Class,Consumer,United States,Atlanta,Georgia,30318,South,Technology,Accessories,499.9800,2,0.00,114.9954
2276,Standard Class,Consumer,United States,Southaven,Mississippi,38671,South,Office Supplies,Storage,306.2000,5,0.00,0.0000
2278,Standard Class,Consumer,United States,Southaven,Mississippi,38671,South,Technology,Accessories,223.9600,4,0.00,53.7504
2290,Standard Class,Corporate,United States,Columbus,Georgia,31907,South,Technology,Phones,287.9700,3,0.00,77.7519
2291,Standard Class,Corporate,United States,Columbus,Georgia,31907,South,Furniture,Furnishings,595.3800,6,0.00,297.6900
2302,Standard Class,Corporate,United States,Columbus,Georgia,31907,South,Technology,Accessories,316.0000,4,0.00,31.6000
2303,Second Class,Home Office,United States,Roswell,Georgia,30076,South,Furniture,Chairs,723.9200,4,0.00,188.2192
2324,Second Class,Corporate,United States,Henderson,Kentucky,42420,South,Office Supplies,Binders,364.8000,12,0.00,167.8080
2399,Standard Class,Corporate,United States,Florence,South Carolina,29501,South,Office Supplies,Storage,628.8100,7,0.00,12.5762
2435,First Class,Corporate,United States,Springfield,Virginia,22153,South,Office Supplies,Appliances,826.1100,3,0.00,322.1829
2448,Second Class,Consumer,United States,North Charleston,South Carolina,29406,South,Office Supplies,Storage,269.4900,3,0.00,5.3898
2467,Standard Class,Consumer,United States,Newport News,Virginia,23602,South,Office Supplies,Storage,571.4400,4,0.00,165.7176
2471,Standard Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Furniture,Bookcases,451.1360,4,0.20,-67.6704
2533,Standard Class,Corporate,United States,Little Rock,Arkansas,72209,South,Technology,Accessories,339.9600,4,0.00,122.3856
2551,Standard Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Furnishings,821.8800,6,0.00,213.6888
2554,Standard Class,Consumer,United States,Tallahassee,Florida,32303,South,Technology,Phones,705.5440,7,0.20,70.5544
2575,Standard Class,Corporate,United States,Columbus,Georgia,31907,South,Office Supplies,Binders,319.9000,5,0.00,156.7510
2577,Standard Class,Corporate,United States,Columbus,Georgia,31907,South,Office Supplies,Appliances,675.1200,3,0.00,290.3016
2579,Standard Class,Home Office,United States,Alexandria,Virginia,22304,South,Office Supplies,Storage,489.9200,8,0.00,0.0000
2593,Second Class,Corporate,United States,Summerville,South Carolina,29483,South,Office Supplies,Binders,327.8400,8,0.00,157.3632
2664,First Class,Consumer,United States,Memphis,Tennessee,38109,South,Furniture,Tables,370.6200,3,0.40,-142.0710
2696,Standard Class,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Machines,821.3000,4,0.50,-16.4260
2697,Standard Class,Home Office,United States,Jacksonville,Florida,32216,South,Technology,Machines,22638.4800,6,0.50,-1811.0784
2713,Standard Class,Consumer,United States,Wilmington,North Carolina,28403,South,Technology,Phones,302.3760,3,0.20,37.7970
2739,First Class,Corporate,United States,Hoover,Alabama,35244,South,Office Supplies,Supplies,477.2400,4,0.00,9.5448
2759,Standard Class,Home Office,United States,Columbus,Georgia,31907,South,Office Supplies,Storage,481.3200,4,0.00,125.1432
2800,First Class,Corporate,United States,Miami,Florida,33180,South,Technology,Phones,783.9600,5,0.20,78.3960
2838,First Class,Consumer,United States,Tallahassee,Florida,32303,South,Technology,Machines,695.7000,2,0.50,-27.8280
2840,Standard Class,Home Office,United States,Chesapeake,Virginia,23320,South,Furniture,Chairs,1139.9200,4,0.00,284.9800
2841,Second Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Office Supplies,Paper,229.5440,7,0.20,83.2097
2848,Standard Class,Corporate,United States,Roswell,Georgia,30076,South,Office Supplies,Binders,2690.9700,3,0.00,1264.7559
2857,Second Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Furniture,Chairs,225.2960,2,0.20,22.5296
2859,Standard Class,Consumer,United States,Atlanta,Georgia,30318,South,Technology,Phones,377.9700,3,0.00,98.2722
2860,Standard Class,Consumer,United States,Atlanta,Georgia,30318,South,Furniture,Bookcases,1628.8200,9,0.00,374.6286
2861,Standard Class,Consumer,United States,Atlanta,Georgia,30318,South,Office Supplies,Paper,286.9300,7,0.00,140.5957
2897,Standard Class,Corporate,United States,Charlotte,North Carolina,28205,South,Technology,Copiers,959.9680,4,0.20,119.9960
2910,Standard Class,Consumer,United States,Coral Springs,Florida,33065,South,Office Supplies,Appliances,387.1360,4,0.20,24.1960
2928,Standard Class,Home Office,United States,Burlington,North Carolina,27217,South,Office Supplies,Binders,1633.1880,4,0.70,-1306.5504
2968,Second Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Office Supplies,Appliances,499.5840,3,0.20,43.7136
2972,Second Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Office Supplies,Storage,259.1360,4,0.20,-51.8272
2978,Second Class,Consumer,United States,Mount Pleasant,South Carolina,29464,South,Furniture,Chairs,545.9400,6,0.00,87.3504
2987,Standard Class,Home Office,United States,Columbus,Georgia,31907,South,Office Supplies,Storage,1267.6500,9,0.00,152.1180
3028,Standard Class,Consumer,United States,Chesapeake,Virginia,23320,South,Furniture,Chairs,504.9000,5,0.00,80.7840
3048,First Class,Home Office,United States,Columbus,Georgia,31907,South,Furniture,Tables,411.8000,2,0.00,70.0060
3049,First Class,Home Office,United States,Columbus,Georgia,31907,South,Technology,Accessories,360.0000,4,0.00,129.6000
3082,Standard Class,Home Office,United States,Louisville,Kentucky,40214,South,Technology,Phones,539.9700,3,0.00,134.9925
3089,Second Class,Home Office,United States,Henderson,Kentucky,42420,South,Technology,Phones,671.9300,7,0.00,188.1404
3118,First Class,Corporate,United States,Lakeland,Florida,33801,South,Furniture,Chairs,1123.9200,5,0.20,-182.6370
3119,First Class,Corporate,United States,Lakeland,Florida,33801,South,Technology,Phones,249.5840,2,0.20,31.1980
3124,First Class,Corporate,United States,Lakeland,Florida,33801,South,Office Supplies,Storage,1036.6240,2,0.20,51.8312
3125,First Class,Corporate,United States,Lakeland,Florida,33801,South,Office Supplies,Storage,563.8080,4,0.20,21.1428
3168,Standard Class,Corporate,United States,Tallahassee,Florida,32303,South,Furniture,Chairs,390.2720,8,0.20,-24.3920
3280,Second Class,Corporate,United States,Alexandria,Virginia,22304,South,Office Supplies,Supplies,4164.0500,5,0.00,83.2810
3320,Standard Class,Consumer,United States,Columbia,Tennessee,38401,South,Furniture,Chairs,662.8800,3,0.20,74.5740
3385,Standard Class,Home Office,United States,Charlotte,North Carolina,28205,South,Office Supplies,Storage,580.6720,4,0.20,65.3256
3387,Standard Class,Home Office,United States,Charlotte,North Carolina,28205,South,Technology,Phones,222.3840,2,0.20,16.6788
3399,Standard Class,Corporate,United States,Richmond,Kentucky,40475,South,Office Supplies,Paper,629.1000,6,0.00,301.9680
3452,Second Class,Home Office,United States,Raleigh,North Carolina,27604,South,Technology,Phones,471.9200,2,0.20,29.4950
3482,First Class,Corporate,United States,Springfield,Virginia,22153,South,Technology,Phones,579.9500,5,0.00,168.1855
3484,First Class,Corporate,United States,Springfield,Virginia,22153,South,Furniture,Tables,1202.9400,3,0.00,300.7350
3499,Standard Class,Consumer,United States,Mobile,Alabama,36608,South,Technology,Accessories,209.9700,3,0.00,71.3898
3518,First Class,Consumer,United States,Fayetteville,North Carolina,28314,South,Office Supplies,Appliances,569.5360,4,0.20,64.0728
3525,Second Class,Home Office,United States,Jackson,Mississippi,39212,South,Technology,Accessories,599.9700,3,0.00,257.9871
3580,Standard Class,Consumer,United States,Jackson,Mississippi,39212,South,Furniture,Tables,2430.0800,8,0.00,388.8128
3588,First Class,Consumer,United States,Lafayette,Louisiana,70506,South,Office Supplies,Supplies,1665.6200,2,0.00,33.3124
3590,Standard Class,Home Office,United States,Richmond,Kentucky,40475,South,Office Supplies,Storage,1443.9600,12,0.00,375.4296
3694,Standard Class,Corporate,United States,Springfield,Virginia,22153,South,Office Supplies,Binders,232.9600,7,0.00,116.4800
3704,Standard Class,Corporate,United States,Decatur,Alabama,35601,South,Technology,Copiers,899.9700,3,0.00,314.9895
3718,Standard Class,Consumer,United States,Columbus,Georgia,31907,South,Technology,Accessories,249.9500,5,0.00,107.4785
3746,Second Class,Consumer,United States,Columbus,Georgia,31907,South,Furniture,Chairs,368.9700,3,0.00,81.1734
3768,Second Class,Corporate,United States,Hialeah,Florida,33012,South,Furniture,Chairs,1013.8320,9,0.20,101.3832
3774,Second Class,Consumer,United States,Miami,Florida,33180,South,Technology,Accessories,383.9760,3,0.20,81.5949
3776,Second Class,Consumer,United States,Miami,Florida,33180,South,Technology,Accessories,335.9440,7,0.20,41.9930
3783,Second Class,Consumer,United States,Memphis,Tennessee,38109,South,Office Supplies,Storage,720.0640,4,0.20,-63.0056
3797,First Class,Consumer,United States,Miami,Florida,33178,South,Office Supplies,Paper,251.6400,3,0.20,88.0740

In [94]:
pd.options.display.max_rows = 10 # = 100 means 100 rows

In [95]:
df[(df['Sales'] > 200) & (df['Region'] == 'South')]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
72,Standard Class,Consumer,United States,Memphis,Tennessee,38109,South,Furniture,Chairs,831.9360,8,0.20,-114.3912
79,First Class,Corporate,United States,Decatur,Alabama,35601,South,Office Supplies,Appliances,208.1600,1,0.00,56.2032
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9769,Standard Class,Home Office,United States,Hialeah,Florida,33012,South,Furniture,Bookcases,339.9200,5,0.20,8.4980
9816,Standard Class,Corporate,United States,Saint Petersburg,Florida,33710,South,Office Supplies,Storage,516.9600,4,0.20,-6.4620
9829,Standard Class,Consumer,United States,Charlotte,North Carolina,28205,South,Furniture,Chairs,242.3520,3,0.20,15.1470
9882,First Class,Consumer,United States,Woodstock,Georgia,30188,South,Technology,Accessories,272.6100,13,0.00,98.1396
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.1000,5,0.00,55.6470

In [104]:
df[(df['Sales'] > 200) & ((df['Region'] == 'South') | (df['Region'] == 'West'))]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.1840,9,0.20,85.3092
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,249.5840,2,0.20,31.1980
9979,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,437.4720,14,0.20,153.1152
9988,Standard Class,Corporate,United States,Athens,Georgia,30605,South,Technology,Phones,206.1000,5,0.00,55.6470
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [105]:
df[(df['Sales'] > 200) & (~(df['Region'] == 'South') | (df['Region'] == 'West'))]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.152,6,0.2,90.7152
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,1706.184,9,0.2,85.3092
11,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,911.424,4,0.2,68.3568
13,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,407.976,3,0.2,132.5922
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.880,6,0.0,13.3176
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9973,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,271.960,5,0.2,27.1960
9976,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Technology,Phones,249.584,2,0.2,31.1980
9979,Standard Class,Home Office,United States,Los Angeles,California,90032,West,Office Supplies,Binders,437.472,14,0.2,153.1152
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.576,2,0.2,19.3932
9993,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.160,2,0.0,72.9480

In [106]:
df[(df['Sales'] > 200) & ~((df['Region'] == 'South') | (df['Region'] == 'West'))]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
16,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,665.8800,6,0.00,13.3176
27,Standard Class,Consumer,United States,Philadelphia,Pennsylvania,19140,East,Furniture,Bookcases,3083.4300,7,0.50,-1665.0522
35,First Class,Corporate,United States,Richardson,Texas,75080,Central,Technology,Phones,1097.5440,7,0.20,123.4737
38,Standard Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,532.3992,3,0.32,-46.9764
39,Standard Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Chairs,212.0580,3,0.30,-15.1470
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9947,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Furniture,Chairs,1925.8800,6,0.00,539.2464
9948,Second Class,Corporate,United States,Indianapolis,Indiana,46203,Central,Office Supplies,Appliances,2405.2000,8,0.00,793.7160
9957,Standard Class,Home Office,United States,New Rochelle,New York,10801,East,Office Supplies,Paper,223.9200,4,0.00,109.7208
9962,First Class,Home Office,United States,Houston,Texas,77041,Central,Furniture,Bookcases,383.4656,4,0.32,-67.6704
9968,Standard Class,Consumer,United States,Plainfield,New Jersey,7060,East,Office Supplies,Binders,735.9800,2,0.00,331.1910

In [107]:
df[['Region', 'Sales']]

     Region     Sales
0     South  261.9600
1     South  731.9400
2      West   14.6200
3     South  957.5775
4     South   22.3680
...     ...       ...
9989  South   25.2480
9990   West   91.9600
9991   West  258.5760
9992   West   29.6000
9993   West  243.1600

[9994 rows x 2 columns]

In [108]:
df.describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [109]:
df.describe(include='all')

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000
unique,4,3,1,531,49,631,4,3,17,NaN,NaN,NaN,NaN
top,Standard Class,Consumer,United States,New York City,California,10035,West,Office Supplies,Binders,NaN,NaN,NaN,NaN
freq,5968,5191,9994,915,2001,263,3203,6026,1523,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,229.858001,3.789574,0.156203,28.656896
...,...,...,...,...,...,...,...,...,...,...,...,...,...
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.280000,2.000000,0.000000,1.728750
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.490000,3.000000,0.200000,8.666500
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,209.940000,5.000000,0.200000,29.364000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.800000,8399.976000

In [110]:
df.loc[
    (df['Sales'] > 200) & ~((df['Region'] == 'South') | (df['Region'] == 'West')),
    ['Region', 'Sales']
]

       Region      Sales
16    Central   665.8800
27       East  3083.4300
35    Central  1097.5440
38    Central   532.3992
39    Central   212.0580
...       ...        ...
9947  Central  1925.8800
9948  Central  2405.2000
9957     East   223.9200
9962  Central   383.4656
9968     East   735.9800

[1310 rows x 2 columns]